/*
 * C32 regression tests — the frontend never rendered `applicability`.
 *
 * 04_FINDINGS_LEDGER.md C32 [E], build item 41: `applicability` appeared
 * exactly once in all of geowatch-ui/src/, at App.jsx:493, as
 * `layer.intersection_type === 'aoi_total_given_layer_applicability'` — an
 * unrelated string comparison. `result.applicability` was never read, and it
 * was not in NAV_SECTIONS (six entries). C14 -> C20 -> C32 is one signal dying
 * three times; items 40 and 41 are the fix for deaths two and three.
 *
 * ACCEPTANCE, from item 41: an AOI that trips `out_of_distribution` produces a
 * UI state the user cannot miss. Three things have to be true for that, and
 * each is asserted below: the banner escalates, the nav entry alerts, and the
 * affected values are named rather than the reader being told "something is
 * wrong somewhere".
 *
 * WHY PLAIN NODE, NO TEST RUNNER. geowatch-ui has no vitest and no
 * @testing-library installed, and tests/FloodAssessmentPanel.test.jsx imports
 * both plus a `../src/FloodAssessmentPanel` module that does not exist — so
 * that file cannot run at all and has never been able to fail. Rather than add
 * a toolchain as a side effect of this item, the reliability LOGIC is kept in
 * a plain module (geowatch-ui/src/applicability.js) that node can import
 * directly. JSX validity is covered separately by `vite build` and `oxlint`,
 * both of which pass with no new findings.
 *
 * FIXTURES COME FROM THE REAL BACKEND. tests/fixtures/*.json are generated by
 * running the actual gate, not hand-written. A hand-written fixture would let
 * the UI test keep passing while the emitted shape moved underneath it — which
 * is C31's exact failure: a JavaScript constant asserted by a Python comment,
 * 0 of 8 matching.
 *
 * Run:  node tests/test_applicability_ui.mjs
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import assert from 'node:assert/strict'

const here = dirname(fileURLToPath(import.meta.url))
const {
  reportApplicability, landcoverTrust, blockFlag, isFlagged, mechanismRows, TRUST_META,
} = await import(join(here, '..', 'geowatch-ui', 'src', 'applicability.js'))

const load = name => JSON.parse(readFileSync(join(here, 'fixtures', `result_${name}.json`), 'utf8'))
const OOD = load('ood')
const DEGRADED = load('degraded')
const CLEAN = load('clean')
const PRE = load('pre_item40')

let passed = 0
const tests = []
const test = (name, fn) => tests.push([name, fn])

/* ── The acceptance criterion ────────────────────────────────────────── */

test('OOD run raises an un-missable alert', () => {
  const app = reportApplicability(OOD)
  assert.equal(app.trust, 'out_of_distribution')
  assert.equal(app.isAlert, true, 'banner must escalate')
  assert.equal(app.severity, 'alert')
  assert.ok(app.meta.headline.length > 0, 'must carry a plain-language headline')
  assert.ok(app.reason, 'must surface the backend reason string')
})

test('OOD nav entry alerts, so it is visible without scrolling', () => {
  // NAV_SECTIONS marks the reliability entry `alertable`; the nav renders a dot
  // and an OOD/WEAK tag when reportApplicability().isAlert is true. The sidebar
  // is always on screen, the banner is not.
  const src = readFileSync(join(here, '..', 'geowatch-ui', 'src', 'App.jsx'), 'utf8')
  assert.match(src, /id: 'reliability'/, 'reliability must be in NAV_SECTIONS')
  assert.match(src, /alertable: true/, 'the reliability nav entry must be alertable')
  assert.match(src, /s\.alertable && reportTrust\.isAlert/, 'nav must react to the alert state')
})

test('affected values are named, not left vague', () => {
  const app = reportApplicability(OOD)
  assert.ok(app.affectedCount > 0, 'something must be named as affected')
  const keys = app.affected.map(a => `${a.group}/${a.key}`)
  // pluvial and waterlogging consume the semantic model; exposure consumes
  // landcover_builtup_pct; risk inherits from hazard + exposure.
  assert.ok(keys.includes('susceptibility/pluvial'), `expected pluvial, got ${keys}`)
  assert.ok(keys.includes('susceptibility/waterlogging'), `expected waterlogging, got ${keys}`)
})

test('unaffected mechanisms are named as unaffected, not silently omitted', () => {
  const app = reportApplicability(OOD)
  const keys = app.unaffected.map(a => `${a.group}/${a.key}`)
  for (const m of ['fluvial', 'coastal', 'flash_flood']) {
    assert.ok(keys.includes(`susceptibility/${m}`),
      `${m} reads independent data and must be listed unaffected, got ${keys}`)
  }
})

/* ── The signal must keep its meaning ───────────────────────────────── */

test('clean run does NOT raise an alert', () => {
  const app = reportApplicability(CLEAN)
  assert.equal(app.trust, 'in_distribution')
  assert.equal(app.isAlert, false,
    'a banner that fires on every run trains readers to skip it')
  assert.equal(app.affectedCount, 0)
})

test('clean run still states that the check happened', () => {
  // Silence would leave a reader unable to tell "checked and fine" from
  // "never checked" — S1's collapse of distinct epistemic states.
  const app = reportApplicability(CLEAN)
  assert.equal(app.hasBlock, true)
  assert.ok(app.meta.headline.includes('within its tested range'))
})

test('degraded is distinct from out_of_distribution', () => {
  const app = reportApplicability(DEGRADED)
  assert.equal(app.trust, 'degraded')
  assert.equal(app.isAlert, true, 'degraded must still be surfaced')
  assert.equal(app.severity, 'warn', 'but at a lower severity than OOD')
  assert.notEqual(app.meta.headline, TRUST_META.out_of_distribution.headline)
})

/* ── Reading, never re-deriving ─────────────────────────────────────── */

test('trust is read from the backend block, not recomputed', () => {
  // Forge a block whose status contradicts what any threshold rule would say.
  // If the UI recomputed from unknown_pct it would disagree — that divergence
  // is C31 (0 of 8 palette categories matching a Python comment's claim).
  const forged = { applicability: { urban_landcover_model: { status: 'degraded', reason: 'forged' } } }
  assert.equal(landcoverTrust(forged), 'degraded')
  const src = readFileSync(join(here, '..', 'geowatch-ui', 'src', 'applicability.js'), 'utf8')
  assert.ok(!/OOD_UNKNOWN_PCT|unknown_pct\s*>/.test(src),
    'the UI must not reimplement the threshold rule')
})

test('per-block flags are read where the number is shown', () => {
  const wl = OOD.susceptibility.waterlogging
  const fl = OOD.susceptibility.fluvial
  assert.ok(blockFlag(wl), 'waterlogging must carry a flag')
  assert.equal(isFlagged(wl), true)
  assert.equal(isFlagged(fl), false, 'fluvial must not be flagged by a landcover failure')
  assert.deepEqual(blockFlag(wl).degraded_by, ['urban_landcover_model'])
})

test('risk inherits the verdict from what it consumed', () => {
  const r = OOD.risk.by_evidence_layer.waterlogging
  const flag = blockFlag(r)
  assert.ok(flag, 'risk block must carry a flag')
  assert.equal(flag.gate, 'inherited')
  assert.equal(flag.out_of_distribution, true)
})

test('values are shown, not withheld (compute-and-flag)', () => {
  const wl = OOD.susceptibility.waterlogging
  assert.ok('aoi_mean_score' in wl, 'the number must survive the OOD verdict')
  assert.notEqual(wl.status, 'withheld')
})

/* ── Absence must not read as approval ──────────────────────────────── */

test('a run with no applicability block reads as NOT CHECKED, not as fine', () => {
  const app = reportApplicability(PRE)
  assert.equal(app.trust, 'unknown')
  assert.equal(app.hasBlock, false)
  assert.equal(app.isAlert, false, 'unknown is not an alert, it is an absence')
  assert.ok(/not checked/i.test(app.meta.headline) || /No reliability verdict/i.test(app.meta.headline),
    `must say no verdict was recorded, got: ${app.meta.headline}`)
  assert.ok(/not as "checked and fine"/.test(app.meta.plain),
    'must explicitly warn against reading absence as approval')
})

test('unflagged blocks are reported as ungated, not as trustworthy', () => {
  const app = reportApplicability(PRE)
  assert.ok(app.ungated.length > 0, 'blocks with no flag must be counted as ungated')
  assert.equal(app.affectedCount, 0)
  assert.equal(app.unaffected.length, 0,
    'an unflagged block must never be classified as unaffected — nobody checked it')
})

test('mechanismRows hides internal keys', () => {
  const rows = mechanismRows(OOD)
  assert.ok(rows.length >= 6, `expected the full mechanism list, got ${rows.length}`)
  assert.ok(!rows.some(r => r.key.startsWith('_')),
    'internal keys such as _hand_context_available must not reach the UI')
  assert.equal(rows.filter(r => r.isRoot).length, 1, 'exactly one root row')
})

/* ── C32's specific claims must no longer hold ──────────────────────── */

test('applicability is no longer a single unrelated string comparison', () => {
  const src = readFileSync(join(here, '..', 'geowatch-ui', 'src', 'App.jsx'), 'utf8')
  const total = (src.match(/applicability/gi) || []).length
  assert.ok(total > 1, `C32 counted exactly 1 occurrence; now ${total}`)
  assert.match(src, /result\?\.applicability|reportApplicability\(/,
    'result.applicability must actually be read')
  assert.match(src, /<ApplicabilityBanner/, 'the banner must be rendered')
  assert.match(src, /<BlockTrustNote/, 'per-block notes must be rendered')
})

/* ── run ─────────────────────────────────────────────────────────────── */

let failed = 0
for (const [name, fn] of tests) {
  try { fn(); passed++; console.log(`  ok    ${name}`) }
  catch (e) { failed++; console.log(`  FAIL  ${name}\n        ${e.message}`) }
}
console.log(`\n${passed} passed, ${failed} failed, ${tests.length} total`)
process.exit(failed === 0 ? 0 : 1)
