<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<!-- Item 21 strata style (LABELLING_GUIDE.md §3). Generated by
     experiments/item21_sites/build_strata_packages.py; do not hand-edit. -->
<qgis version="3.28" styleCategories="Symbology|Fields|Forms">
  <renderer-v2 type="categorizedSymbol" attr="stratum" symbollevels="0" enableorderby="0" forceraster="0">
    <categories>
      <category symbol="0" value="dense_informal" label="dense_informal" render="true"/>
      <category symbol="1" value="formal" label="formal" render="true"/>
      <category symbol="2" value="mixed" label="mixed" render="true"/>
      <category symbol="3" value="fringe" label="fringe" render="true"/>
    </categories>
    <symbols>
      <symbol type="fill" name="0" alpha="0.4" clip_to_extent="1" force_rhr="0">
        <layer class="SimpleFill" enabled="1" locked="0" pass="0">
          <Option type="Map">
            <Option name="color" type="QString" value="215,48,31,255"/>
            <Option name="outline_color" type="QString" value="215,48,31,255"/>
            <Option name="outline_style" type="QString" value="solid"/>
            <Option name="outline_width" type="QString" value="0.6"/>
            <Option name="style" type="QString" value="solid"/>
          </Option>
        </layer>
      </symbol>
      <symbol type="fill" name="1" alpha="0.4" clip_to_extent="1" force_rhr="0">
        <layer class="SimpleFill" enabled="1" locked="0" pass="0">
          <Option type="Map">
            <Option name="color" type="QString" value="33,113,181,255"/>
            <Option name="outline_color" type="QString" value="33,113,181,255"/>
            <Option name="outline_style" type="QString" value="solid"/>
            <Option name="outline_width" type="QString" value="0.6"/>
            <Option name="style" type="QString" value="solid"/>
          </Option>
        </layer>
      </symbol>
      <symbol type="fill" name="2" alpha="0.4" clip_to_extent="1" force_rhr="0">
        <layer class="SimpleFill" enabled="1" locked="0" pass="0">
          <Option type="Map">
            <Option name="color" type="QString" value="128,125,186,255"/>
            <Option name="outline_color" type="QString" value="128,125,186,255"/>
            <Option name="outline_style" type="QString" value="solid"/>
            <Option name="outline_width" type="QString" value="0.6"/>
            <Option name="style" type="QString" value="solid"/>
          </Option>
        </layer>
      </symbol>
      <symbol type="fill" name="3" alpha="0.4" clip_to_extent="1" force_rhr="0">
        <layer class="SimpleFill" enabled="1" locked="0" pass="0">
          <Option type="Map">
            <Option name="color" type="QString" value="65,171,93,255"/>
            <Option name="outline_color" type="QString" value="65,171,93,255"/>
            <Option name="outline_style" type="QString" value="solid"/>
            <Option name="outline_width" type="QString" value="0.6"/>
            <Option name="style" type="QString" value="solid"/>
          </Option>
        </layer>
      </symbol>
    </symbols>
  </renderer-v2>
  <fieldConfiguration>
    <field name="stratum" configurationFlags="None">
      <editWidget type="ValueMap">
        <config>
          <Option type="Map">
            <Option name="map" type="List">
              <Option type="Map"><Option name="dense_informal" type="QString" value="dense_informal"/></Option>
              <Option type="Map"><Option name="formal" type="QString" value="formal"/></Option>
              <Option type="Map"><Option name="mixed" type="QString" value="mixed"/></Option>
              <Option type="Map"><Option name="fringe" type="QString" value="fringe"/></Option>
            </Option>
          </Option>
        </config>
      </editWidget>
    </field>
  </fieldConfiguration>
  <constraints>
    <constraint field="stratum" constraints="1" notnull_strength="1" unique_strength="0" exp_strength="0"/>
  </constraints>
</qgis>
