"""
QGIS style and empty template for a label layer (LABELLING_GUIDE.md §1, §2,
§5; guide v1.1 rooftop-solar flag).

    layer "labels", polygons in the site's UTM CRS, fields:
      label           text  -- Value Map: the guide's scored + excluded labels
      shadow_partial  bool  -- §1/§5: the underlying surface plus this flag
      rooftop_solar   bool  -- v1.1: only on `built`
      note            text  -- free text for the labeller

Categorised fill per label at 40% opacity so the imagery stays visible while
tracing; the two flags are checkboxes; `label` may not be null.
"""

from __future__ import annotations

LAYER = "labels"
FIELDS = ["label", "shadow_partial", "rooftop_solar", "note"]
COLOURS = {                                  # one per label; excluded labels muted
    "built": "215,48,31", "paved": "99,99,99", "vegetation": "49,163,84",
    "water": "33,113,181", "bare": "217,164,65", "mixed_water_vegetation": "0,150,150",
    "snow_ice": "220,220,255", "solar": "117,107,177",
    "unsure": "255,255,0", "shadow_full": "30,30,30",
}


def labels_qml(labels: list) -> str:
    cats = "\n".join(f'      <category symbol="{i}" value="{s}" label="{s}" render="true"/>'
                     for i, s in enumerate(labels))
    syms = "\n".join(f'''      <symbol type="fill" name="{i}" alpha="0.4" clip_to_extent="1" force_rhr="0">
        <layer class="SimpleFill" enabled="1" locked="0" pass="0">
          <Option type="Map">
            <Option name="color" type="QString" value="{COLOURS[s]},255"/>
            <Option name="outline_color" type="QString" value="{COLOURS[s]},255"/>
            <Option name="outline_style" type="QString" value="solid"/>
            <Option name="outline_width" type="QString" value="0.4"/>
            <Option name="style" type="QString" value="solid"/>
          </Option>
        </layer>
      </symbol>''' for i, s in enumerate(labels))
    vmap = "\n".join(f'              <Option type="Map"><Option name="{s}" type="QString" value="{s}"/></Option>'
                     for s in labels)
    checkbox = '''      <editWidget type="CheckBox">
        <config><Option type="Map">
          <Option name="CheckedState" type="QString" value="1"/>
          <Option name="UncheckedState" type="QString" value="0"/>
        </Option></config>
      </editWidget>'''
    return f'''<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<!-- Item 21 label-layer style (LABELLING_GUIDE.md). Generated by
     labelling/label_style.py; do not hand-edit. -->
<qgis version="3.28" styleCategories="Symbology|Fields|Forms">
  <renderer-v2 type="categorizedSymbol" attr="label" symbollevels="0" enableorderby="0" forceraster="0">
    <categories>
{cats}
    </categories>
    <symbols>
{syms}
    </symbols>
  </renderer-v2>
  <fieldConfiguration>
    <field name="label" configurationFlags="None">
      <editWidget type="ValueMap">
        <config>
          <Option type="Map">
            <Option name="map" type="List">
{vmap}
            </Option>
          </Option>
        </config>
      </editWidget>
    </field>
    <field name="shadow_partial" configurationFlags="None">
{checkbox}
    </field>
    <field name="rooftop_solar" configurationFlags="None">
{checkbox}
    </field>
  </fieldConfiguration>
  <constraints>
    <constraint field="label" constraints="1" notnull_strength="1" unique_strength="0" exp_strength="0"/>
  </constraints>
</qgis>
'''


def empty_labels_gdf(crs: str):
    import geopandas as gpd
    import pandas as pd
    return gpd.GeoDataFrame({"label": pd.Series([], dtype="object"),
                             "shadow_partial": pd.Series([], dtype="bool"),
                             "rooftop_solar": pd.Series([], dtype="bool"),
                             "note": pd.Series([], dtype="object")},
                            geometry=gpd.GeoSeries([], crs=crs), crs=crs)
