"""
QGIS style for the item 21 strata layer (LABELLING_GUIDE.md §3).

strata_qml() -> the QML stored as the default style inside strata.gpkg
(labelling/strata_rule.py) and shipped as strata.qml: a categorised fill per
stratum at 40% opacity, `unassigned` as an outline only, and a Value Map
dropdown on "stratum" limited to the four strata plus `unassigned`, with a
not-null constraint.
"""

COLOURS = {                                  # distinct, colour-blind-safe-ish
    "dense_informal": "215,48,31",
    "formal": "33,113,181",
    "mixed": "128,125,186",
    "fringe": "65,171,93",
}


UNASSIGNED = "unassigned"          # drafted by the rule; never sampled; outline only


def strata_qml(strata: list) -> str:
    values = list(strata) + [UNASSIGNED]
    cats = "\n".join(f'      <category symbol="{i}" value="{s}" label="{s}" render="true"/>'
                     for i, s in enumerate(values))
    syms = "\n".join(f'''      <symbol type="fill" name="{i}" alpha="0.4" clip_to_extent="1" force_rhr="0">
        <layer class="SimpleFill" enabled="1" locked="0" pass="0">
          <Option type="Map">
            <Option name="color" type="QString" value="{COLOURS[s]},255"/>
            <Option name="outline_color" type="QString" value="{COLOURS[s]},255"/>
            <Option name="outline_style" type="QString" value="solid"/>
            <Option name="outline_width" type="QString" value="0.6"/>
            <Option name="style" type="QString" value="solid"/>
          </Option>
        </layer>
      </symbol>''' for i, s in enumerate(strata)) + f'''
      <symbol type="fill" name="{len(strata)}" alpha="1" clip_to_extent="1" force_rhr="0">
        <layer class="SimpleFill" enabled="1" locked="0" pass="0">
          <Option type="Map">
            <Option name="color" type="QString" value="0,0,0,0"/>
            <Option name="outline_color" type="QString" value="255,255,255,255"/>
            <Option name="outline_style" type="QString" value="solid"/>
            <Option name="outline_width" type="QString" value="0.4"/>
            <Option name="style" type="QString" value="no"/>
          </Option>
        </layer>
      </symbol>'''
    vmap = "\n".join(f'''              <Option type="Map"><Option name="{s}" type="QString" value="{s}"/></Option>'''
                     for s in values)
    return f'''<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<!-- Item 21 strata style (LABELLING_GUIDE.md §3). Generated by
     experiments/item21_sites/build_strata_packages.py; do not hand-edit. -->
<qgis version="3.28" styleCategories="Symbology|Fields|Forms">
  <renderer-v2 type="categorizedSymbol" attr="stratum" symbollevels="0" enableorderby="0" forceraster="0">
    <categories>
{cats}
    </categories>
    <symbols>
{syms}
    </symbols>
  </renderer-v2>
  <fieldConfiguration>
    <field name="stratum" configurationFlags="None">
      <editWidget type="ValueMap">
        <config>
          <Option type="Map">
            <Option name="map" type="List">
{vmap}
            </Option>
          </Option>
        </config>
      </editWidget>
    </field>
  </fieldConfiguration>
  <constraints>
    <constraint field="stratum" constraints="1" notnull_strength="1" unique_strength="0" exp_strength="0"/>
  </constraints>
</qgis>
'''
